
-- local coq = require "coq"
-- lsp.<server>.setup(coq.lsp_ensure_capabilities())
-- local capabilities = vim.lsp.protocol.make_client_capabilities()
-- local capabilities = coq.lsp_ensure_capabilities()
-- local lspSetup = {
--     on_attach = on_attach,
--     flags = {
--         -- This will be the default in neovim 0.7+
--         debounce_text_changes = 150,
--         composites = false,
--     },
--     settings = {
--         gopls = {
--             analyses = {
--                 unusedparams = true,
--                 composites = false,
--             },
--             staticcheck = true,
--         }
--     },
--     capabilities = capabilities
-- }
